[package]
name = "twitch-hls-client"
version = "1.0.1"
authors = ["2bc4 <119853089+2bc4@users.noreply.github.com>"]
description = "Minimal CLI client for watching low latency Twitch streams"
license = "GPL-3.0-or-later"
repository = "https://github.com/2bc4/twitch-hls-client"
edition = "2021"
rust-version = "1.75"

[lints.rust]
unsafe_code = "forbid"
warnings = "deny"

[lints.clippy]
pedantic = "deny"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true

[features]
default = ["colors"]
colors = []
http2 = ["curl/http2"]
static-curl = ["curl/static-curl"]
static-openssl = ["curl/static-ssl"]

[dependencies]
anyhow = "1.0.79"
curl = { version = "0.4.44", git = "https://github.com/alexcrichton/curl-rust.git", rev = "0c1dddf" }
fastrand = "2.0.1"
log = { version = "0.4.20", features = ["std"] }
pico-args = { version = "0.5.0", features = ["eq-separator"] }
time = { version = "0.3.31", features = ["local-offset", "formatting", "macros"] }
url = "2.5.0"
