[package]
name = "twitch-hls-client"
version = "0.3.1"
authors = ["2bc4 <119853089+2bc4@users.noreply.github.com>"]
description = "Lightweight CLI client for watching low latency Twitch streams with ad blocking"
license = "GPL-3.0-or-later"
repository = "https://github.com/2bc4/twitch-hls-client"
edition = "2021"
rust-version = "1.60"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = "symbols"

[features]
default = ["rustls-webpki"]
rustls-webpki = ["dep:rustls", "dep:webpki-roots"]
rustls-native-certs = ["dep:rustls", "dep:rustls-native-certs"]
native-tls = ["dep:native-tls"]

[dependencies]
anyhow = "1.0.71"
chunked_transfer = "1.4.1"
clap = { version = "4.2.7", default-features = false, features = ["std", "help", "usage", "error-context", "cargo"] }
flate2 = "1.0.26"
httparse = "1.8.0"
log = "0.4.17"
native-tls = { version = "0.2.11", optional = true }
percent-encoding = "2.2.0"
rustls = { version = "0.21.1", optional = true }
rustls-native-certs = { version = "0.6.2", optional = true }
simplelog = "0.12.1"
time = "0.3.21"
url = "2.3.1"
webpki-roots = { version = "0.23.0", optional = true }
