[package]
name = "twitch-hls-client"
version = "0.5.6"
authors = ["2bc4 <119853089+2bc4@users.noreply.github.com>"]
description = "Lightweight CLI client for watching low latency Twitch streams with ad blocking"
license = "GPL-3.0-or-later"
repository = "https://github.com/2bc4/twitch-hls-client"
edition = "2021"
rust-version = "1.75"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
curl = { version = "0.4.44", features = ["http2"] }
log = "0.4.20"
pico-args = { version = "0.5.0", features = ["eq-separator"] }
rand = "0.8.5"
serde_json = "1.0.108"
simplelog = "0.12.1"
time = "0.3.30"
url = "2.5.0"
