[package]
name = "twitch-hls-client"
version = "0.5.3"
authors = ["2bc4 <119853089+2bc4@users.noreply.github.com>"]
description = "Lightweight CLI client for watching low latency Twitch streams with ad blocking"
license = "GPL-3.0-or-later"
repository = "https://github.com/2bc4/twitch-hls-client"
edition = "2021"
rust-version = "1.60"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[features]
default = ["rustls-webpki"]
rustls-webpki = ["dep:rustls", "dep:webpki-roots"]
rustls-native-certs = ["dep:rustls", "dep:rustls-native-certs"]
native-tls = ["dep:native-tls"]

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
chunked_transfer = "1.4.1"
flate2 = "1.0.28"
httparse = "1.8.0"
log = "0.4.20"
native-tls = { version = "0.2.11", optional = true }
pico-args = "0.5.0"
rand = "0.8.5"
rustls = { version = "0.21.7", optional = true }
rustls-native-certs = { version = "0.6.3", optional = true }
serde_json = "1.0.107"
simplelog = "0.12.1"
time = "0.3.30"
url = "2.4.1"
webpki-roots = { version = "0.23.1", optional = true }
