[package]
name = "twitch-hls-client"
version = "0.2.1"
authors = ["2bc4 <119853089+2bc4@users.noreply.github.com>"]
description = "Lightweight CLI client for watching low latency Twitch streams with ad blocking"
license = "GPL-3.0-or-later"
repository = "https://github.com/2bc4/twitch-hls-client"
edition = "2021"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[dependencies]
anyhow = "1.0.70"
chunked_transfer = "1.4.1"
clap = { version = "4.2.1", default-features = false, features = ["std", "help", "usage", "error-context", "cargo"] }
flate2 = "1.0.25"
httparse = "1.8.0"
is-terminal = "0.4.6"
log = "0.4.17"
percent-encoding = "2.2.0"
rustls = "0.21.0"
rustls-native-certs = "0.6.2"
simplelog = "0.12.1"
time = "0.3.20"
url = "2.3.1"
