[package]
name = "twitch-hls-client"
version = "0.5.6"
authors = ["2bc4 <119853089+2bc4@users.noreply.github.com>"]
description = "A minimal (and buggy) low latency HLS client for Twitch"
license = "GPL-3.0-or-later"
repository = "https://github.com/2bc4/twitch-hls-client"
edition = "2021"
rust-version = "1.60"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
log = "0.4.20"
once_cell = "1.19.0"
pico-args = { version = "0.5.0", features = ["eq-separator"] }
rand = "0.8.5"
reqwest = { version = "0.11.23", default-features = false, features = ["json", "blocking", "gzip", "rustls-tls", "rustls-native-certs"] }
serde_json = "1.0.108"
simplelog = "0.12.1"
time = "0.3.30"
url = "2.5.0"
