# Based on https://github.com/AlyoshaVasilieva/luminous-ttv/blob/main/.github/workflows/wf.yaml

on:
  push:
    paths:
      - '**.rs'
      - 'Cargo**'
  pull_request:
    paths:
      - '**.rs'
      - 'Cargo**'

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo check --no-default-features --features rustls-webpki
      - run: cargo check --no-default-features --features rustls-native-certs
      - run: cargo check --no-default-features --features native-tls

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --all --no-default-features --features rustls-webpki -- -Wclippy::pedantic -Dwarnings
      - run: cargo clippy --all --no-default-features --features rustls-native-certs -- -Wclippy::pedantic -Dwarnings
      - run: cargo clippy --all --no-default-features --features native-tls -- -Wclippy::pedantic -Dwarnings
